### PR TITLE
Implementation of PSNR-B metric

### PR DESCRIPTION
**Pull request by sachinpuranik99**
Hello Andrew,

Thanks for doing the amazing job of setting this repo with different metrics for Image Quality Assessment. I have added the code for PSNR-B metric as part of this PR. The code was originally written in Matlab and I have translated it for Python with few bugfixes by referring to the original [Quality Assessment of Deblocked Images](https://ieeexplore.ieee.org/abstract/document/5535179)

This PR fixes the [issue](https://github.com/andrewekhalel/sewar/issues/4)

I have not added any unit tests for the PSNR-B, please let me know if you want me to add them for this PR to get approved.

### CODE REVIEW

**Comment by andrewekhalel** [comment]
Hello @sachinpuranik99,

Great job! Thanks for adding PSNR-B. I will just need you to add at least one unit test to compare with values obtained from matlab code to your implementation (Check sewar/tests/ directory).

Thanks,
Andrew

**Comment by sachinpuranik99** [comment]
Hello @andrewekhalel,

I have added the tests for checking PSNR-B w.r.t MATLAB. The tests are passing as of now with Python 3.6, scipy1.1 and latest Pillow

**Comment by andrewekhalel** [comment]
Awesome! one more thing to do, I think PSNR-B belongs to the full reference category of metrics, am I right? If yes, please move the implementation to "full_ref.py".

Many Thanks.

**Comment by andrewekhalel** [comment]
Also, would you please update "command_line.py" and "README.md" to support the command line instructions? If you need any help, just let me know.

**Comment by sachinpuranik99** [comment]
@sachinpuranik99 Sure, I will update the command_line and README. Can you tell me what's the difference between the full_ref and no_ref?

**Comment by andrewekhalel** [comment]
Definitely.
Full reference metrics are comparing two images together the original (reference) and altered images, for example PSNR and SSIM. On the other hand, no reference metrics don't need a reference image for comparison.

**Comment by sachinpuranik99** [comment]
@andrewekhalel  Thanks for the explanation. I have moved the PSNR-B from no-ref to full-ref. I have added updated the CLI support for the same and added the CLI tests. I have updated the README with PSNR-B support. 

I probably don't have access to updating the documentation, let me know otherwise and I would be happy to update it.

**Comment by andrewekhalel** [comment]
Thanks @sachinpuranik99!

**Pull request merged**
